name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Ubah ke branch yang Anda gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Create .env.production file
      run: |
        echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

    - name: Build Docker image
      run: |
        docker build --env-file .env.production -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/24001143-synrgy7-dhs-bcr_api_docs-ch6:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/24001143-synrgy7-dhs-bcr_api_docs-ch6:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy 24001143-synrgy7-dhs-bcr_api_docs-ch6 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/24001143-synrgy7-dhs-bcr_api_docs-ch6:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
