name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Ubah ke branch yang Anda gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Check gcloud authentication
      run: |
        gcloud auth list
        gcloud config list

    - name: Create .env.production file
      run: |
        echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

    - name: Build Docker image
      run: |
        docker build --build-arg ENV_PRODUCTION="$(cat .env.production)" -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/24001143-synrgy7-dhs-bcr_api_docs-ch:latest .

    - name: Push Docker image
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/24001143-synrgy7-dhs-bcr_api_docs-ch:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy 24001143-synrgy7-dhs-bcr_api_docs-ch \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/24001143-synrgy7-dhs-bcr_api_docs-ch/api-bcr-challenge8-synrgy:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
